<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>index.phtml</title>
</head>
<style type="text/css">
    h1{
        color: green;
    }
</style>
<body>
<h1>hello {$name} this is smarty template index/info23456</h1>
{$smarty.now|date_format:'%Y-%m-%d %H:%M:%S'}


</body>
</html>